apiVersion: v1
kind: Service
metadata:
  name: service-myapp-jib
  labels:
    app: myapp
spec:
  selector:
    app: myapp
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: NodePort
