apiVersion: v1
kind: Service
metadata:
  name: service-myapp-provider
  labels:
    app: myapp-provider
spec:
  selector:
    app: myapp-provider
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: NodePort
