apiVersion: skaffold/v2alpha2
kind: Config
metadata:
  name: myapp
build:
  artifacts:
    - image: albertoimpl/myapp
      jib: {}
deploy:
  kustomize:
    path: k8s/base

profiles:
  - name: development
    deploy:
      kustomize:
        path: k8s/overlays/development
  - name: production
    deploy:
      kustomize:
        path: k8s/overlays/production
