apiVersion: v1
kind: Service
metadata:
  name: service-myapp-consumer
  labels:
    app: myapp-consumer
spec:
  selector:
    app: myapp-consumer
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: NodePort
